### ISSUE TITLE
WSL 子系统的工作环境下不能正常运行

### ISSUE THREAD

**Issue by imnodb** [aliyun-node/agentx#106]
```
ENOENT: no such file or directory, open '/proc/sys/kernel/core_pattern'
Error: ENOENT: no such file or directory, open '/proc/sys/kernel/core_pattern'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.exports.init (/home/db/.tnvm/versions/alinode/v3.14.1/lib/node_modules/@alicloud/agenthub/node_modules/agentx/lib/orders/list_core.js:182:19)
```
因为WSL存在一个已知问题，导致读取文件出错。
[参考](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/20464948-make-core-dump-files-available-in-wsl)

**Comment by hyj1991** [comment]
这个错误并不会影响 `agentx` 的工作，不过确实可以加一个判断更加友好一些
