### ISSUE TITLE
agentx 安装报错

### ISSUE THREAD

**Issue by shanelau** [aliyun-node/agentx#25]
本地 node 版本 0.12.7

https://npm.taobao.org/mirrors/node/v0.13.0/node-v0.13.0.tar.gz  确实是404

```

[root@bigertechA ~]# cnpm install agentx -g
|
> utf-8-validate@1.2.1 install /root/.tnvm/versions/alinode/v0.3.1/lib/node_modules/agentx/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://npm.taobao.org/mirrors/node/v0.13.0/node-v0.13.0.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/lib/install.js:244:14)
gyp ERR! stack     at Request.emit (events.js:131:20)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/node_modules/request/request.js:998:10)
gyp ERR! stack     at ClientRequest.emit (events.js:109:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:428:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:113:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:319:20)
gyp ERR! stack     at TLSSocket.emit (events.js:109:17)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:164:16)
gyp ERR! stack     at TLSSocket.Readable.push (_stream_readable.js:128:10)
gyp ERR! System Linux 2.6.32-358.el6.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.tnvm/versions/alinode/v0.3.1/lib/node_modules/agentx/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.13.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
```

最后的结果 

```
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing bufferutil@1.2.1
/root/.tnvm/versions/alinode/v0.3.1/bin/agentx -> /root/.tnvm/versions/alinode/v0.3.1/lib/node_modules/agentx/start_client.js
agentx@1.2.4 /root/.tnvm/versions/alinode/v0.3.1/lib/node_modules/agentx
├── nounou@1.0.1
├── split2@0.2.1
├── debug@2.2.0 (ms@0.7.1)
├── through2@0.6.5 (xtend@4.0.1, readable-stream@1.0.33)
└── ws@0.8.1 (options@0.0.6, ultron@1.0.2)
```

这算成功还是失败呢？

**Comment by shanelau** [comment]
不过  agentx 还是跑起来了。

**Comment by JacksonTian** [comment]
@yjhjstz 将这个问题修复了再发布个0.3.2版？

**Comment by JacksonTian** [comment]
建议你使用最新的版本了 1.1.1来安装agentx

**Comment by JacksonTian** [comment]
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing bufferutil@1.2.1

这两个依赖安装失败了，但降级到了JS的版本上。

**Comment by shanelau** [comment]
@JacksonTian 我的业务是跑的 0.12.7 ， 一直半会没法升级到 node 4.x 或者 5.x 版本。

**Comment by yjhjstz** [comment]
已修复，重新安装下`alinode-v0.3.2`即可。
