### ISSUE TITLE
安装 agentx 失败

### ISSUE THREAD

**Issue by wengcd** [aliyun-node/agentx#47]
## env
`alinode-v2.0.8 with Node.js v6.9.5`

`npm install agentx -g`

## 如下结果
```
SyntaxError: Unexpected token C in JSON at position 19
    at Object.parse (native)
    at /root/.tnvm/versions/alinode/v2.0.8/lib/node_modules/npm/node_modules/uid-number/uid-number.js:43:18
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by JacksonTian** [comment]
```sh
ENABLE_NODE_LOG=NO npm install agentx -g
```

这个问题是由于环境变量中默认了ENABLE_NODE_LOG=YES，但没有设置NODE_LOG_DIR的值，导致alinode运行时会打印一个警告，然后导致解析stdout的模块出错了。通过在执行命令前设置`ENABLE_NODE_LOG=NO`临时关闭这个检查。

**Comment by wengcd** [comment]
我应该设置了 `NODE_LOG_DIR=/tmp/`

**Comment by JacksonTian** [comment]
嗯 设置了 权限有问题之类的，都会有一条警告，导致stdout的问题。
