### ISSUE TITLE
需要先判断文件是否存在。

### ISSUE THREAD

**Issue by JacksonTian** [aliyun-node/agentx#76]
```
2018-04-18 16:44:01,879 ERROR 108558 nodejs.Error: Command failed: cat /proc/63968/environ
cat: /proc/63968/environ: 权限不够

cat: /proc/63968/environ: 权限不够

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
killed: false
code: 1
signal: null
cmd: 'cat /proc/63968/environ'
pid: 108558
```

63968 已经不存在。

**Comment by zhangzifa** [comment]
什么机器? 我本地ubuntu上的结果

```sh
![image](https://user-images.githubusercontent.com/7731478/38921996-b68861b8-4329-11e8-8c0c-9e648ee3d019.png)

```

**Comment by viko16** [comment]
同样遇到。

另外遇到这样的异常，是否也是类似的问题呢？

```
2018-08-29 08:50:32,090 ERROR 207 nodejs.ENOENTError: ENOENT: no such file or directory, scandir '/storage/logs/coredump'
Error: ENOENT: no such file or directory, scandir '/storage/logs/coredump'
errno: -2
code: "ENOENT"
syscall: "scandir"
path: "/storage/logs/coredump"
name: "ENOENTError"
pid: 207
```

**Comment by zhangzifa** [comment]
@viko16 你的agentx版本？

**Comment by viko16** [comment]
@zhangzifa 由 egg-alinode 引入
- agentx 1.9.11
- egg-alinode 2.0.1
- node 8.11.3

**Comment by zhangzifa** [comment]
`/storage/logs/coredump` 这个目录存在吗？

**Comment by viko16** [comment]
@zhangzifa 这个目录不存在

**Comment by zhangzifa** [comment]
这个是你配置的目录？还是agentx自己识别出来的目录？

另外：如果配置了不存在的目录，每次扫描的时候，都会写这条日志，但是功能上没影响
